---
# 2.2 and 2.4 are supported on RHEL 6, only 2.4 is support on RHEL 7
apache_version: "{{ '2.4' if ansible_distribution_major_version == '7' else '2.2' }}"
apache_from_scl: "{{ ansible_distribution_major_version == '6' and apache_version == '2.4' }}"
apache_original_root_dir: "{{ '/opt/rh/httpd24/root' if apache_from_scl else '' }}"
apache_service: "{{ 'httpd24-httpd' if apache_from_scl else 'httpd' }}"
apache_rehome_default_target: "httpd"
apache_rehome_scl_target: "httpd{{ apache_version.split('.')[0:2] | join('') }}"
apache_rehome_target: "{{ apache_rehome_scl_target if apache_from_scl else apache_rehome_default_target }}"

apache_original_conf_dir: "{{ apache_original_root_dir }}/etc/httpd"
apache_httpd_dir: "{{ env_etc }}/{{ apache_rehome_target }}"
apache_conf_dir: "{{ apache_httpd_dir }}/conf"
apache_confd_dir: "{{ apache_httpd_dir }}/conf.d"
apache_conf_modulesd_dir: "{{ apache_httpd_dir }}/conf.modules.d"
apache_vhostsd_dir: "{{ apache_httpd_dir }}/vhosts.d"
apache_sysconfig: "{{ apache_original_root_dir }}/etc/sysconfig/httpd"

apache_original_doc_dir: "{{ apache_original_root_dir }}/var/www"
apache_doc_dir: "{{ env_var }}/www"
apache_document_root: "{{ apache_doc_dir }}/html"
apache_log_dir: "{{ env_var_log }}/{{ apache_rehome_target }}"

apache_modules_dir: "{{ apache_original_root_dir }}/usr/lib64/httpd/modules"
apache_run_dir: "{{ apache_original_root_dir }}/var/run/httpd"

apache_admin_email: "root@localhost"

apache_user: "{{ env_user }}"
apache_group: "{{ env_group }}"
apache_dir_mode: "{{ env_dir_mode }}"
apache_file_mode: "{{ env_file_mode }}"
apache_key_mode: "0660"
apache_ssl_certificate_key_passphrase: null

apache_httpd_process_user: "apache"
apache_httpd_process_group: "apache"

apache_log_processor_executable: "/usr/sbin/cronolog"
apache_log_processor_dir_structure: "%Y/%m/"
apache_error_log: "\"|{{ apache_log_processor_executable }} {{ apache_log_dir }}/{{ apache_log_processor_dir_structure }}error_log\""
apache_custom_log: "\"|{{ apache_log_processor_executable }} {{ apache_log_dir }}/{{ apache_log_processor_dir_structure }}access_log\" combined"

apache_vhost_error_log: "\"|{{ apache_log_processor_executable }} {{ apache_log_dir }}/{{ apache_log_processor_dir_structure }}{{item.server_name }}_error_log\""

apache_vhost_custom_log: "\"|{{ apache_log_processor_executable }} {{ apache_log_dir }}/{{ apache_log_processor_dir_structure }}{{item.server_name }}_access_log\" combined"

apache_vhost_request_log: "\"|{{ apache_log_processor_executable }} {{ apache_log_dir }}/{{ apache_log_processor_dir_structure }}{{item.server_name }}_request_log\" \\\n
      \"%t %h \\\"%r\\\" %b\""

apache_vhost_ssl_error_log: "\"|{{ apache_log_processor_executable }} {{ apache_log_dir }}/{{ apache_log_processor_dir_structure }}ssl_{{item.server_name }}_error_log\""

apache_vhost_ssl_custom_log: "\"|{{ apache_log_processor_executable }} {{ apache_log_dir }}/{{ apache_log_processor_dir_structure }}ssl_{{item.server_name }}_access_log\" combined"

apache_vhost_ssl_request_log: "\"|{{ apache_log_processor_executable }} {{ apache_log_dir }}/{{ apache_log_processor_dir_structure }}ssl_{{item.server_name }}_request_log\" \\\n
      \"%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \\\"%r\\\" %b\""

apache_sysv_restart_command: "sudo /sbin/service {{ apache_service }} graceful"
apache_systemd_restart_command: "sudo systemctl restart {{ apache_service }}"
apache_restart_command: "{{ apache_sysv_restart_command if ansible_distribution_major_version == '6' else apache_systemd_restart_command }}"

apache_mod_ssl_config_file: "{{ apache_confd_dir }}/ssl.conf"
apache_mod_ssl_conf_modulesd_dir: "{{ apache_conf_modulesd_dir }}"
apache_mod_ssl_listen_ports: [443]
apache_mod_ssl_pass_dialog: "exec:{{ '/opt/rh/httpd24/root' if apache_from_scl else '' }}/usr/libexec/httpd-ssl-pass-dialog"

apache_vhosts: []
apache_ssl_enabled_vhosts: "{{ apache_vhosts|selectattr('use_ssl', 'defined')|selectattr('use_ssl')|list }}"
apache_enable_ssl: "{{ apache_ssl_enabled_vhosts|length > 0 }}"
apache_vhost_ssl_certs_dir: "{{ env_etc }}/pki/tls/certs"
apache_vhost_ssl_keys_dir: "{{ env_etc }}/pki/tls/private"
apache_vhost_ssl_certificate_interm_cer_file: "{{ apache_vhost_ssl_certs_dir }}/umn_interm.cer"
apache_vhost_ssl_std_file: "{{ apache_conf_dir }}/ssl_standard.conf"

apache_vhost_ssl_cipher_suites:
  - "ECDHE-RSA-AES128-GCM-SHA256"
  - "ECDHE-ECDSA-AES128-GCM-SHA256"
  - "ECDHE-RSA-AES256-GCM-SHA384"
  - "ECDHE-ECDSA-AES256-GCM-SHA384"
  - "DHE-RSA-AES128-GCM-SHA256"
  - "DHE-DSS-AES128-GCM-SHA256"
  - "kEDH+AESGCM"
  - "ECDHE-RSA-AES128-SHA256"
  - "ECDHE-ECDSA-AES128-SHA256"
  - "ECDHE-RSA-AES128-SHA"
  - "ECDHE-ECDSA-AES128-SHA"
  - "ECDHE-RSA-AES256-SHA384"
  - "ECDHE-ECDSA-AES256-SHA384"
  - "ECDHE-RSA-AES256-SHA"
  - "ECDHE-ECDSA-AES256-SHA"
  - "DHE-RSA-AES128-SHA256"
  - "DHE-RSA-AES128-SHA"
  - "DHE-DSS-AES128-SHA256"
  - "DHE-RSA-AES256-SHA256"
  - "DHE-DSS-AES256-SHA"
  - "DHE-RSA-AES256-SHA"
  - "AES128-GCM-SHA256"
  - "AES256-GCM-SHA384"
  - "AES128-SHA256"
  - "AES256-SHA256"
  - "AES128-SHA"
  - "AES256-SHA"
  - "AES"
  - "CAMELLIA"
  - "DES-CBC3-SHA"
  - "!aNULL"
  - "!eNULL"
  - "!EXPORT"
  - "!DES"
  - "!RC4"
  - "!MD5"
  - "!PSK"
  - "!aECDH"
  - "!EDH-DSS-DES-CBC3-SHA"
  - "!EDH-RSA-DES-CBC3-SHA"
  - "!KRB5-DES-CBC3-SHA"
