---
- name: Deploy certificate chain file
  copy:
    content: "{{ apache_vhost_item.ssl_certificate_interm_cer | default(lookup('file', 'umn_sha2_interm.cer')) }}"
    dest: "{{ apache_vhost_ssl_certs_dir }}/{{ apache_vhost_item_interm_cer_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: "{{ apache_file_mode }}"
  notify: restart apache

- name: Deploy certificates
  copy:
    content: "{{ apache_vhost_item.ssl_certificate_cer }}"
    dest: "{{ apache_vhost_ssl_certs_dir }}/{{ apache_vhost_item_cer_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: "{{ apache_file_mode }}"
  notify: restart apache

  # Need to get modulus after deploying updated certificates to the server
- name: Get modulus from certificate
  command: "openssl x509 -noout -modulus -in {{ apache_vhost_ssl_certs_dir }}/{{ apache_vhost_item_cer_file }}"
  register: apache_ssl_certificate_remote_cer_modulus
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"
  check_mode: no

- name: Get modulus from key
  shell: "test -f {{ apache_vhost_ssl_keys_dir }}/{{ apache_vhost_item_key_file }} && openssl rsa -noout -modulus -in {{ apache_vhost_ssl_keys_dir }}/{{ apache_vhost_item_key_file }}"
  register: apache_ssl_certificate_remote_key_modulus
  changed_when: false
  failed_when: false
  check_mode: no

- name: Deploy encrypted key file
  copy:
    content: "{{ apache_vhost_item.ssl_certificate_key }}"
    dest: "{{ apache_vhost_ssl_keys_dir }}/{{ apache_vhost_item_key_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: "{{ apache_key_mode }}"
  when: "apache_ssl_certificate_remote_key_modulus.stdout != apache_ssl_certificate_remote_cer_modulus.stdout or apache_ssl_certificate_remote_cer_modulus|failed"

- name: Decrypt key
  no_log: false
  shell: >
    openssl pkcs8 -topk8 -in {{ apache_vhost_ssl_keys_dir }}/{{ apache_vhost_item_key_file }} -out {{ apache_vhost_ssl_keys_dir }}/{{ apache_vhost_item_key_file }}.decrypted -nocrypt -passin env:ANSIBLE_APACHE_KEY_PASS && mv {{ apache_vhost_ssl_keys_dir }}/{{ apache_vhost_item_key_file }}.decrypted {{ apache_vhost_ssl_keys_dir }}/{{ apache_vhost_item_key_file }}
  notify: restart apache
  environment:
    ANSIBLE_APACHE_KEY_PASS: "{{ apache_ssl_certificate_key_passphrase }}"
  when: "apache_ssl_certificate_remote_key_modulus.stdout != apache_ssl_certificate_remote_cer_modulus.stdout or apache_ssl_certificate_remote_cer_modulus|failed"

- name: Verify key permissions
  file:
    path: "{{ apache_vhost_ssl_keys_dir }}/{{  apache_vhost_item_key_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: "{{ apache_key_mode }}"
  ignore_errors: "{{ ansible_check_mode }}"
