- name: Ensure ssl is enabled if a vhost uses ssl
  fail:
    msg: "apache_enable_ssl must be true if a vhost uses ssl. This role will automatically set apache_enable_ssl based off vhosts if it is not overriden."
  when: not apache_enable_ssl and (apache_vhosts|selectattr('use_ssl', 'defined')|selectattr('use_ssl')|list|length > 0)
  tags:
    - apache

- name: Create global standard ssl configuration
  template:
    src: "vhost-ssl-std.conf.j2"
    dest: "{{ apache_vhost_ssl_std_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: "{{ apache_file_mode }}"

- name: Install vhost configurations
  template:
    src: "vhost.conf.j2"
    dest: "{{ apache_vhostsd_dir }}/vhost-{{ item.server_name }}.conf"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: "{{ apache_file_mode }}"
  with_items: "{{ apache_vhosts }}"
  notify: "restart apache"

