---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  role_name: env
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_pip: true
  ansible_version: "2.1"

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: default
  - name: standard

# Why this magic number for max_ssh_sessions? To prevent errors like this:
#
# Transferring files to <default-centos-73>
# /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-3.2.0/lib/net/ssh/connection/channel.rb:541:in `do_open_failed': open failed (1) (Net::SSH::ChannelOpenFailed)
#
# Other test kitchen users have encountered similar errors, at least on Linux
# and have also reported success with this work-around. More details here:
# https://github.com/test-kitchen/test-kitchen/issues/1035#issuecomment-283189967
transport:
  max_ssh_sessions: 6
