---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  role_name: apache
  hosts: all
  require_chef_for_busser: false
  require_ruby_for_busser: false
  additional_copy_path: "test/integration/files/"
  require_pip: true
  ansible_version: "2.2"

verifier:
  name: inspec

platforms:
  - name: centos-6.7
  - name: centos-7.2

suites:
  - name: default
  - name: scl24
    excludes:
      - centos-7.2
    provisioner:
      extra_vars:
        apache_version: "2.4"
  - name: enable-mod-ssl
    excludes:
      - centos-6.7
    
