---
- name: "update firewall rules"
  become: true
  ipset:
    name: "{{ item }}"
    members: "{{ ipset_ips }}"
  when: ansible_distribution_major_version == '7'
  with_items: "{{ ipset_rule_names }}"
  tags:
    ipset

