---
# We are checking for the existence of the directory
# before we create it to ensure we don't stomp on existing
# system directories. Normally, you would not do this and instead
# just rely on the file module to create the directory if it does
# not exist
- name: "check existence of {{ env_dir }}"
  stat:
    path: "{{ env_dir }}"
  register: dir

- name: "create {{ env_dir }}"
  file:
    path: "{{ env_dir }}"
    state: directory
    owner: "{{ env_user }}"
    group: "{{ env_group }}"
    mode: "{{ env_dir_mode }}"
  when: env_dir | regex_search("^/swadm") or not dir.stat.exists or dir.stat.isreg
